In [39]:
import numpy as np

# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original matrix:")
print(matrix)

# Sum along axis 0 (columns)
sum_axis_0 = np.sum(matrix, axis=0)
print("Sum along axis 0 (columns):")
print(sum_axis_0)

# Sum along axis 1 (rows)
sum_axis_1 = np.sum(matrix, axis=1)
print("Sum along axis 1 (rows):")
print(sum_axis_1)

# Mean along axis 0 (columns)
mean_axis_0 = np.mean(matrix, axis=0)
print("Mean along axis 0 (columns):")
print(mean_axis_0)

# Mean along axis 1 (rows)
mean_axis_1 = np.mean(matrix, axis=1)
print("Mean along axis 1 (rows):")
print(mean_axis_1)

# Creating a 3D array (tensor)
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]],
                   [[9, 10], [11, 12]]])

print("Original tensor:")
print(tensor)

# Sum along axis 0 (depth)
sum_axis_0_3d = np.sum(tensor, axis=0)
print("Sum along axis 0 (depth) in 3D tensor:")
print(sum_axis_0_3d)

# Sum along axis 1 (rows)
sum_axis_1_3d = np.sum(tensor, axis=1)
print("Sum along axis 1 (rows) in 3D tensor:")
print(sum_axis_1_3d)

# Sum along axis 2 (columns)
sum_axis_2_3d = np.sum(tensor, axis=2)
print("Sum along axis 2 (columns) in 3D tensor:")
print(sum_axis_2_3d)


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum along axis 0 (columns):
[12 15 18]
Sum along axis 1 (rows):
[ 6 15 24]
Mean along axis 0 (columns):
[4. 5. 6.]
Mean along axis 1 (rows):
[2. 5. 8.]
Original tensor:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Sum along axis 0 (depth) in 3D tensor:
[[15 18]
 [21 24]]
Sum along axis 1 (rows) in 3D tensor:
[[ 4  6]
 [12 14]
 [20 22]]
Sum along axis 2 (columns) in 3D tensor:
[[ 3  7]
 [11 15]
 [19 23]]
