In [38]:
import numpy as np

# Array Creation
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
zeros_array = np.zeros((3, 4))
ones_array = np.ones((2, 3))
range_array = np.arange(10)
linspace_array = np.linspace(0, 1, 5)

# Basic Operations
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
sum_array = array_a + array_b
mult_array = array_a * array_b
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
transpose_matrix = np.transpose(matrix_a)

# Statistical Operations
stats_array = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(stats_array)
median_value = np.median(stats_array)
std_dev = np.std(stats_array)
sum_value = np.sum(stats_array)

# Reshaping and Indexing
reshaped_array = np.reshape(np.arange(12), (3, 4))
element = reshaped_array[0, 1]
first_row = reshaped_array[0, :]
first_column = reshaped_array[:, 0]
sliced_array = reshaped_array[:2, -2:]

# Advanced Operations
exp_array = np.exp(array_a)
sqrt_array = np.sqrt(array_a)
concatenated_array = np.concatenate((array_a, array_b))
broadcast_array = array_a + 10

# Display all results
print("1D Array:", array_1d)
print("2D Array:", array_2d)
print("Array of zeros:", zeros_array)
print("Array of ones:", ones_array)
print("Array with a range of values:", range_array)
print("Array with evenly spaced values:", linspace_array)
print("Sum of arrays:", sum_array)
print("Element-wise multiplication of arrays:", mult_array)
print("Matrix multiplication:", matrix_product)
print("Transpose of a matrix:", transpose_matrix)
print("Mean value:", mean_value)
print("Median value:", median_value)
print("Standard deviation:", std_dev)
print("Sum of array elements:", sum_value)
print("Reshaped array (3x4):", reshaped_array)
print("Element at (0, 1):", element)
print("First row:", first_row)
print("First column:", first_column)
print("Sliced array (first two rows, last two columns):", sliced_array)
print("Exponential of each element in the array:", exp_array)
print("Square root of each element in the array:", sqrt_array)
print("Concatenated array:", concatenated_array)
print("Broadcasting (adding 10 to each element):", broadcast_array)


1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]
Array of zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of ones: [[1. 1. 1.]
 [1. 1. 1.]]
Array with a range of values: [0 1 2 3 4 5 6 7 8 9]
Array with evenly spaced values: [0.   0.25 0.5  0.75 1.  ]
Sum of arrays: [5 7 9]
Element-wise multiplication of arrays: [ 4 10 18]
Matrix multiplication: [[19 22]
 [43 50]]
Transpose of a matrix: [[1 3]
 [2 4]]
Mean value: 3.0
Median value: 3.0
Standard deviation: 1.4142135623730951
Sum of array elements: 15
Reshaped array (3x4): [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at (0, 1): 1
First row: [0 1 2 3]
First column: [0 4 8]
Sliced array (first two rows, last two columns): [[2 3]
 [6 7]]
Exponential of each element in the array: [ 2.71828183  7.3890561  20.08553692]
Square root of each element in the array: [1.         1.41421356 1.73205081]
Concatenated array: [1 2 3 4 5 6]
Broadcasting (adding 10 to each element): [11 12 13]
